*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /NRK/LAPAYUSERTOP.                 " Global Data
  INCLUDE /NRK/LAPAYUSERUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /NRK/LAPAYUSERF00                       . " subprograms
  INCLUDE /NRK/LAPAYUSERI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /NRK/LAPAYUSERF...                 " Subprograms
* INCLUDE /NRK/LAPAYUSERO...                 " PBO-Modules
* INCLUDE /NRK/LAPAYUSERI...                 " PAI-Modules
