*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /NRK/LAPAYEDEFTOP.                 " Global Data
  INCLUDE /NRK/LAPAYEDEFUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /NRK/LAPAYEDEFF00                       . " subprograms
  INCLUDE /NRK/LAPAYEDEFI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /NRK/LAPAYEDEFF...                 " Subprograms
* INCLUDE /NRK/LAPAYEDEFO...                 " PBO-Modules
* INCLUDE /NRK/LAPAYEDEFI...                 " PAI-Modules
