*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /NRK/LAPAYVCODETOP.                " Global Data
  INCLUDE /NRK/LAPAYVCODEUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /NRK/LAPAYVCODEF00                      . " subprograms
  INCLUDE /NRK/LAPAYVCODEI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /NRK/LAPAYVCODEF...                " Subprograms
* INCLUDE /NRK/LAPAYVCODEO...                " PBO-Modules
* INCLUDE /NRK/LAPAYVCODEI...                " PAI-Modules
