*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /NRK/LAPAYSDEFTOP.                 " Global Data
  INCLUDE /NRK/LAPAYSDEFUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /NRK/LAPAYSDEFF00                       . " subprograms
  INCLUDE /NRK/LAPAYSDEFI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /NRK/LAPAYSDEFF...                 " Subprograms
* INCLUDE /NRK/LAPAYSDEFO...                 " PBO-Modules
* INCLUDE /NRK/LAPAYSDEFI...                 " PAI-Modules
