*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /NRK/LAPAYDTYPETOP.                " Global Data
  INCLUDE /NRK/LAPAYDTYPEUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /NRK/LAPAYDTYPEF00                      . " subprograms
  INCLUDE /NRK/LAPAYDTYPEI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /NRK/LAPAYDTYPEF...                " Subprograms
* INCLUDE /NRK/LAPAYDTYPEO...                " PBO-Modules
* INCLUDE /NRK/LAPAYDTYPEI...                " PAI-Modules
