*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /NRK/LAPAYCONFIGTOP.               " Global Data
  INCLUDE /NRK/LAPAYCONFIGUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /NRK/LAPAYCONFIGF00                     . " subprograms
  INCLUDE /NRK/LAPAYCONFIGI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /NRK/LAPAYCONFIGF...               " Subprograms
* INCLUDE /NRK/LAPAYCONFIGO...               " PBO-Modules
* INCLUDE /NRK/LAPAYCONFIGI...               " PAI-Modules
